"""LSH band columns for pHash candidate lookup.

Eight generated byte-band columns over the 64-bit perceptual hash. By the
pigeonhole principle, two hashes within Hamming distance 7 agree exactly on
at least one band, so indexed band-equality finds every candidate pair for
the default threshold (6) without O(n^2) comparison.

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-04

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for band in range(8):
        column = f"phash_b{band}"
        op.add_column(
            "photos",
            sa.Column(
                column,
                sa.SmallInteger(),
                sa.Computed(f"((phash >> {band * 8}) & 255)::smallint", persisted=True),
                nullable=True,
            ),
        )
        op.create_index(f"ix_photos_{column}", "photos", [column])


def downgrade() -> None:
    for band in range(8):
        op.drop_index(f"ix_photos_phash_b{band}")
        op.drop_column("photos", f"phash_b{band}")
